[certificates]
aws_bucket = "codeforgood-certificates"
aws_region = "eu-central-1"
mtls_subdir = "endpoints/mtls/esro"
ssl_subdir = "endpoints/local.wecodeforgood.com"

[api]
url = "https://esro.localhost:443/api"
domain = "local.wecodeforgood.com"
port = 8443

[cloud]
aws_bucket = "esro"

